### ISSUE TITLE
TwBlue not authorising account 

### ISSUE THREAD

**Issue by RunningLeopard2** [manuelcortez/TWBlue#236] opened 2018-07-18 17:55 UTC
Hi there Manual.

Attempted to reinstall the latest version of twBlue from your website and for some reason it only says 
"waiting for authorization"
When I try to authorize my account.
Is this perhaps the Whitelist URL issue that was occuring with TheQube a few days ago?

Thanks for all the good work on both the clients.

**Comment by Mohamed00** [comment] 2018-07-18 21:55
Twitter made a change to how authorization works that meant it had to revert to PIN authorization. At the moment you have to download a snapshot at https://twblue.es/pubs/snapshot.zip. However you can use it just to authorize your account, copy the config folder from the snapshots directory to %appdata%\TW Blue and switch back to the stable version.

**Comment by codeofdusk** [comment] 2018-07-19 03:06
Duplicate of #230.

Bill

**Closed as completed** 2018-07-19 17:24 UTC
