### ISSUE TITLE
TWBlue refusing to send the tweet although it is less than 280 characters

### ISSUE THREAD

**Issue by fawazar94** [manuelcortez/TWBlue#441] opened 2021-11-18 05:29 UTC
So today I was sending a tweet, then got this error:

400 Bad Request
The length of the `text` field in the request body [482] is not between 0 and 280
The reason might be the lengthy link. I was able to send the tweet successfully from the web.
In these cases, can we get the edit box back with the written text instead of just giving the error?
It is somewhat hard to remember the exact wording to retype it once more.
Here the tweet link:
https://twitter.com/fawazar94/status/1461202804073287680
thanks.

**Comment by maikoroizz** [comment] 2021-12-01 09:38
Hola, TWBlue no permite subir imágenes al hacer tweets. solo deja por dm.
También TWBlue da problemas a la hora de hacer tweets, Se cierra y no se hace el tweets.

**Comment by jmdaweb** [comment] 2021-12-01 20:56
Hola, @maikoroiz.
Hemos recibido tu mensaje las 300 veces que lo has enviado por 300 sitios distintos. @manuelcortez puede dedicarse a este proyecto menos que antes por motivos de trabajo, y yo puedo hacerlo aún menos. Por favor, deja de insistir. Ya sabemos que no puedes subir fotos ni vídeos. No te preocupes, trabajaremos en ello cuando sea posible. De verdad, te lo prometo. Te sugiero que la próxima vez que escribas por aquí lo hagas abriendo una nueva incidencia, y si es posible en inglés. No todo el mundo puede entender el español, y debemos ser coherentes con el idioma principal del proyecto.
Un saludo.

**Comment by maikoroizz** [comment] 2021-12-04 04:02
Hola estimado.
Hemos recibido su mensaje.

Lamentamos su actitud totalmente fuera de adherencia.

 le exigimos por favor mantener un verbo considerado ante los clientes.

 De igual manera recalcamos las deficiencias que en la última versión
han empañado la extraordinaria función que venía desempeñando dicha
aplicación.



Nos despedimos deseándole una feliz navidad!

 Hello dear.
We have received your message.

We regret your attitude totally out of adherence.

 We ask you to please maintain a considerate attitude towards our customers.

 We would also like to emphasize the deficiencies that in the latest
version have tarnished the extraordinary function that this
application had been performing.



We bid you a Merry Christmas!

2021-12-01 17:56 GMT-03:00, José Manuel Delicado ***@***.***>:

**Comment by manuelcortez** [comment] 2021-12-09 15:10
Hi there @fawazar94. Sorry you had this issue. Could you please help me to understand, did you try to add a link to a specific tweet, and that's why you've got this error?

**Comment by manuelcortez** [comment] 2021-12-09 15:32
@fawazar94 Sorry for the misunderstanding. I have repeated the same you did in your Tweet and I am basically unable to reproduce it. I can send tweets with 256 characters plus a link (which counts as 23 chars according to Twitter docs) just fine.

**Comment by fawazar94** [comment] 2021-12-10 09:01
Strangely I couldn't reproduce it now too; However, As I said I was able to send the same tweet from web with no issues. Anyway in such cases can we get the written tweet back after the error message? thanks.

**Comment by manuelcortez** [comment] 2021-12-10 23:33
that's a bit weird, but it's also consistent with my tests. Regarding opening the dialog if the tweet fails, it'll be handled after #377 is closed. So closing it in favour of that issue, where we hope to handle all the discussion.

**Closed as completed by manuelcortez** 2021-12-10 23:33 UTC
