### ISSUE TITLE
when adding accounts the authorization does not come up in the browser as expected.

### ISSUE THREAD

**Issue by mdyer1** [manuelcortez/TWBlue#229] opened 2018-07-11 18:28 UTC
When first launching TW blue, the add account manager comes up, but when the new account manager comes up the message that the account authorization  will open in your browser  will pop up but when selecting yes, nothing happens.  Using 0.93 in windows 10 in 1803.

**Comment by Mohamed00** [comment] 2018-07-11 18:32
Duplicate of #228, please see the comments in that issue for the solution to this problem.

**Comment by sukiletxe** [comment] 2018-07-11 19:05
I believe this is a duplicate of #228. See there for an answer. Closing, reopen if this is not the case, and / or comment if you need more clarification.

**Closed as completed by sukiletxe** 2018-07-11 19:05 UTC
