### ISSUE TITLE
When playing audio files, the end of the file does not play.

### ISSUE THREAD

**Issue by KevanGP** [manuelcortez/TWBlue#344] opened 2020-12-29 07:11 UTC
Hello,
I noticed a bug, when playing MP3 audio files, the last second or so of the file is chopped off and does not play when using TWBlue.

**Comment by KevanGP** [comment] 2020-12-29 07:18
I was just able to reproduce this with a WAV file, too. I imagine it happens with other file types.

**Comment by manuelcortez** [comment] 2021-05-07 21:54
Hi,
Are you testing with the last snapshot version or did you use a stable version to see those results? I am unable to reproduce the issue here.

**Comment by manuelcortez** [comment] 2021-09-11 22:40
closing as we did not have more information for a while.

**Closed as completed by manuelcortez** 2021-09-11 22:40 UTC
