### ISSUE TITLE
Wrong URL opening on quoted tweets

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#184] opened 2017-11-15 08:25 UTC
If user A quoted user B, and user be have URL in tweet,  alt+windows+enter  opening user B tweet on Twitter,, instead to open corresponding URL given in that tweet.

**Comment by Mohamed00** [comment] 2017-11-15 08:38
Duplicate of #167.

**Comment by Mohamed00** [comment] 2017-11-15 21:44
It seems this issue is still open...

**Comment by agasoft** [comment] 2017-11-15 21:46
Its solved. Will try to close it.

**Closed as completed** 2017-11-15 21:46 UTC
